version: '3'
services:
    server_http:
        build:
            context: ./server-http
            dockerfile: Dockerfile
        volumes:
            - ./server-http:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        ports:
            - "80:3000"
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
            - server_rsocket_publisher
            - server_rsocket_consumer
        env_file:
            - .env
    server_rsocket_publisher:
        build:
            context: ./server-rsocket-publisher
            dockerfile: Dockerfile
        volumes:
            - ./server-rsocket-publisher:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
        env_file:
            - .env
    server_rsocket_consumer:
        build:
            context: ./server-rsocket-consumer
            dockerfile: Dockerfile
        volumes:
            - ./server-rsocket-consumer:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
            - server_rsocket_publisher
        env_file:
            - .env
    netifi-broker:
        image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
        ports:
            - "8101:8101"
        networks:
            - netifi_rsocket_example_net
        environment:
            - "BROKER_SERVER_OPTS=-Dnetifi.broker.ssl.disabled=${NETIFI_BROKER_SSL_DISABLED} -Dnetifi.broker.cluster.clusterName=${NETIFI_BROKER_CLUSTER_CLUSTERNAME} -Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN} -Dnetifi.broker.admin.accessKey=${NETIFI_BROKER_ADMIN_ACCESSKEY} -Dnetifi.broker.admin.accessToken=${NETIFI_BROKER_ADMIN_ACCESSTOKEN} -Dnetifi.broker.admin.address=0.0.0.0 -Dnetifi.broker.admin.publicAddress=127.0.0.1 -Dnetifi.broker.admin.port=6001 -Dnetifi.broker.cluster.address=0.0.0.0 -Dnetifi.broker.cluster.publicAddress=127.0.0.1 -Dnetifi.broker.cluster.port=7001 -Dnetifi.broker.tcp.address=0.0.0.0 -Dnetifi.broker.tcp.publicAddress=127.0.0.1 -Dnetifi.broker.tcp.port=8001 -Dnetifi.broker.websocket.address=0.0.0.0 -Dnetifi.broker.websocket.publicAddress=127.0.0.1 -Dnetifi.broker.websocket.port=8101"
networks:
    netifi_rsocket_example_net:
        driver: bridge
