version: "3"
services:
    server_http:
        build:
            context: ./server-http
            dockerfile: Dockerfile
        volumes:
            - ./server-http:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        ports:
            - "80:3000"
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
            - server_rsocket_publisher
            - server_rsocket_consumer
        env_file:
            - .env

    server_rsocket_publisher:
        build:
            context: ./server-rsocket-publisher
            dockerfile: Dockerfile
        volumes:
            - ./server-rsocket-publisher:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
        env_file:
            - .env

    server_rsocket_consumer:
        build:
            context: ./server-rsocket-consumer
            dockerfile: Dockerfile
        volumes:
            - ./server-rsocket-consumer:/usr/src/app
            - ./shared/generated:/usr/src/app/generated
        networks:
            - netifi_rsocket_example_net
        depends_on:
            - netifi-broker
            - server_rsocket_publisher
        env_file:
            - .env

    netifi-broker:
        image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
        ports:
            - "8101:8101"
            - "8888:8888"
        networks:
            - netifi_rsocket_example_net
        environment:
            - "BROKER_SERVER_OPTS=-Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN}"
            - SSL_DISABLED=true
            - METRICS_BIND_ADDRESS=0.0.0.0
            - METRICS_BIND_PORT=8888
            - ADMIN_ACCESS_KEY=9007199254740991
            - ADMIN_ACCESS_TOKEN=kTBDVtfRBO4tHOnZzSyY5ym2kfY=
            - ADMIN_PORT=6001
            - CLUSTER_ADDRESS=0.0.0.0
            - CLUSTER_PUBLIC_ADDRESS=127.0.0.1
            - CLUSTER_PORT=7001
            - BROKER_ADDRESS=0.0.0.0
            - BROKER_PUBLIC_ADDRESS=127.0.0.1
            - BROKER_PORT=8001
            - WEBSOCKET_BROKER_ADDRESS=0.0.0.0
            - WEBSOCKET_BROKER_PUBLIC_ADDRESS=127.0.0.1
            - WEBSOCKET_BROKER_PORT=8101
            - PROMETHEUS_BRIDGE=true
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/:/etc/prometheus/
            - ./.prometheus_data:/prometheus
        networks:
            - netifi_rsocket_example_net
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
        restart: always

    grafana:
        image: grafana/grafana
        user: "104"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./.grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        env_file:
            - ./grafana/config.monitoring
        networks:
            - netifi_rsocket_example_net
        restart: always

networks:
    netifi_rsocket_example_net:
        driver: bridge

volumes:
    prometheus_data:
    grafana_data:
